package com.example.dailycookingapplication.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006877)
val md_theme_light_onPrimary = Color(0xFF006877)
val md_theme_light_primaryContainer = Color(0xFFA4EEFF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFF006877)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFFF6C69)
val md_theme_light_onSurfaceVariant = Color(0xFFEFF1F2)
val md_theme_light_outline = Color(0xFFEFF1F2)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F2)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inversePrimary = Color(0xFF52D7F0)
val md_theme_light_surfaceTint = Color(0xFF006877)
val md_theme_light_outlineVariant = Color(0xFFBFC8CB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF000000)
val md_theme_dark_onPrimary = Color(0xFF00363F)
val md_theme_dark_primaryContainer = Color(0xFF004E5A)
val md_theme_dark_onPrimaryContainer = Color(0xFFA4EEFF)
val md_theme_dark_surface = Color(0xFF191C1D)
val md_theme_dark_onSurface = Color(0xFFE1E3E4)
val md_theme_dark_surfaceVariant = Color(0xFF3F484B)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CB)
val md_theme_dark_outline = Color(0xFF899295)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E4)
val md_theme_dark_inversePrimary = Color(0xFF006877)
val md_theme_dark_surfaceTint = Color(0xFF52D7F0)
val md_theme_dark_outlineVariant = Color(0xFF3F484B)
val md_theme_dark_scrim = Color(0xFF000000)